### ISSUE TITLE
including this app in f-droid.org

### ISSUE THREAD

**Issue by eighthave** [h-mdm/hmdm-android#27]
I would like to include Headwind MDM in the f-droid.org collection of free software apps.  We like to ask whether the app author has any objections.  Also, for smooth integration, we recommend that the apps:

* Use Git tags for all releases
* Include the app store metadata and translations in the app's git repo via Fastlane or Triple-T Gradle Play Plugin.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14668

**Comment by h-mdm** [comment]
The app author has no objections to include Headwind MDM in the f-droid.org collection of free software apps. 

I should however note that Headwind MDM distributed as an installable APK has limitations, also it requires registration on our cloud MDM server (https://srv.h-mdm.com) or deployment of the user's own MDM server. Which means the user may be confused when he just installs Headwind MDM APK from f-droid.org without additional instructions.

We will mark further releases by Git tags because it's a good practice.

Regarding reproducible builds, please note that we are unable to publish our signing keys due to risks of appearance of malware apps signed by our keys and compromising them.

**Comment by licaon-kter** [comment]
As the repro link above explains, F-Droid picks up your signed APK directly once reproducibility is verified, it does not handle keys and signing. :)

**Comment by eighthave** [comment]
I added this text to the desciption to guide users:

>  Headwind MDM requires registration on the Headwind cloud MDM server
>  (https://srv.h-mdm.com) or deployment of the user's own MDM server. See
>  the Headwind MDM documentation for more information.

**Comment by eighthave** [comment]
We want to support free software MDMs like yours, so including it here is a bit experimental.  We're open to suggestions for how best F-Droid can support MDM apps.

**Comment by h-mdm** [comment]
> I added this text to the desciption to guide users:
> 
> > Headwind MDM requires registration on the Headwind cloud MDM server
> > (https://srv.h-mdm.com) or deployment of the user's own MDM server. See
> > the Headwind MDM documentation for more information.

Thank you for the collaboration! I think the own MDM server would be the main way for Headwind MDM Community users. It worth adding the download link (https://h-mdm.com/download/) instead of a link to srv.h-mdm.com (which is mainly used as a demo for Premium customers).

**Comment by eighthave** [comment]
I changed the last paragraph to:

>  Headwind MDM requires registration on a Headwind MDM server.  You
>  can deploy your own (https://h-mdm.com/download/) or try the demo
>  (https://srv.h-mdm.com). See the Headwind MDM documentation for more
>  information.
